from __future__ import annotations

SLOT_STEP_MIN = 15
DEFAULT_SOLVER_TIME_LIMIT_SEC = 3.0
DEFAULT_SEARCH_WORKERS = 4
DEFAULT_HORIZON_DAYS = 3
DEADLINE_GRACE_HOURS = 8
MAX_CANDIDATE_SLOTS_PER_TASK = 80

COST_SCALE = 1000
QUIETNESS_MARGIN = 0.05
DEEP_WORK_LOAD_THRESHOLD = 0.7
DEEP_WORK_BLOCK_THRESHOLD = 0.75
UNSCHEDULED_BASE_PENALTY = 50_000
DEEP_WORK_OVERAGE_COST_PER_MIN = 180
PREFERENCE_WINDOW_PENALTY = 1400
HARD_QUIETNESS_THRESHOLD = 0.92
